apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: homework
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              command: ["echo",  "Hello"]
          activeDeadlineSeconds: 10
          restartPolicy: OnFailure

