apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    name: nginx-rs
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dns
  template:
    metadata:
      labels:
        app: nginx-dns
    spec:
      hostname: nginx-dns
      subdomain: nginx-dns-headless-service      
      containers:
      - image: nginx 
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
